esphome:
  name: "case_light_ganymed"
  platform: ESP32
  board: esp32dev
  on_boot:
    then:
      - light.turn_on:
          id: light_strip
          brightness: 100%
          effect: "Rainbow"

globals:
  - id: light_state
    type: int
    restore_value: no
    initial_value: '0'

logger:
  level: WARN

wifi:
  ssid: "Kerberos"
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret ota_password

light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO13
    type: GRB
    color_correct: [100%, 100%, 100%]
    num_leds: 16
    internal: true
    id: light_strip
    name: "Lichtstreifen"
    effects:
    - addressable_rainbow:
        name: Rainbow
    - addressable_color_wipe:
        name: Color Wipe
        colors:
        - red: 100%
          green: 0%
          blue: 0%
          num_leds: 16
        - red: 0%
          green: 100%
          blue: 0%
          num_leds: 16
        - red: 0%
          green: 0%
          blue: 100%
          num_leds: 16
        add_led_interval: 500ms
    - addressable_color_wipe:
        name: White
        colors:
        - red: 100%
          green: 100%
          blue: 100%
          num_leds: 16
        add_led_interval: 50ms

binary_sensor:
  - platform: gpio
    id: mode_switch
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
    on_release:
      then:
      - lambda: |-
          id(light_state) = (id(light_state) + 1) % 3;
          auto call = id(light_strip).turn_on();
          call.set_brightness(1.0);
          switch(id(light_state)) {
            case 1:
              call.set_effect("White");
              break;
            case 2:
              call.set_effect("Color Wipe");
              break;
            default:
              call.set_effect("Rainbow");
          }
          call.perform();
