substitutions:
  device_name: sensor-arbeitszimmer
  room_name: Arbeitszimmer
  home_power_sensor: "netz_leistung_1min_schnitt"
  battery_power_sensor: venus_garage_leistung
  window_open_sensor: "irgendein_fenster"


<<: !include common.yaml
