substitutions:
  device_name: schlafzimmer
  room_name: Schlafzimmer

  ip_address: 10.13.37.15
  gateway: 10.13.37.1
  subnet: 255.255.255.0
  wifi_ssid: Kerberos
  wifi_password: !secret wifi_password_jan

  sensor1_name: Außen
  sensor1_id: garten
  sensor2_name: Arbeit
  sensor2_id: arbeitszimmer
  sensor3_name: Joris
  sensor3_id: joris
  sensor4_name: Wohn
  sensor4_id: wohnzimmer

<<: !include common.yaml
