esphome:
  name: wohnzimmer
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "Kerberos"
  password: !secret wifi_password

  manual_ip:
    static_ip: 10.13.37.14
    gateway: 10.13.37.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

font:
  - file: "DejaVuSans.ttf"
    id: font_m
    size: 38
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÜÖ abcdefghijklmnopqrstuvwxyzäüöß'
  - file: "DejaVuSans.ttf"
    id: font_l
    size: 64
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÜÖ abcdefghijklmnopqrstuvwxyzäüöß'

mcp23017:
  - id: mcp23017_hub
    address: 0x20

i2c:

sensor:
  - platform: homeassistant
    id: az_temp
    entity_id: sensor.arbeitszimmer_temperatur
  - platform: homeassistant
    id: az_hum
    entity_id: sensor.arbeitszimmer_luftfeuchte

binary_sensor:
  - platform: gpio
    name: "Inkplate Touch Pad 1"
    internal: true
    pin:
      mcp23xxx: mcp23017_hub
      number: 10
  - platform: gpio
    name: "Inkplate Touch Pad 2"
    internal: true
    pin:
      mcp23xxx: mcp23017_hub
      number: 11
  - platform: gpio
    name: "Inkplate Touch Pad 3"
    internal: true
    pin:
      mcp23xxx: mcp23017_hub
      number: 12

display:
  - platform: inkplate6
    id: main_display
    greyscale: false
    partial_updating: true
    update_interval: 10s
    full_update_every: 30
    rotation: 0°
    ckv_pin: 32
    sph_pin: 33
    gmod_pin:
      mcp23xxx: mcp23017_hub
      number: 1
    gpio0_enable_pin:
      mcp23xxx: mcp23017_hub
      number: 8
    oe_pin:
      mcp23xxx: mcp23017_hub
      number: 0
    spv_pin:
      mcp23xxx: mcp23017_hub
      number: 2
    powerup_pin:
      mcp23xxx: mcp23017_hub
      number: 4
    wakeup_pin:
      mcp23xxx: mcp23017_hub
      number: 3
    vcom_pin:
      mcp23xxx: mcp23017_hub
      number: 5
    lambda: |-
      it.fill(COLOR_ON);

      it.strftime(10,  80, id(font_l), COLOR_OFF, TextAlign::BASELINE_LEFT, "%H:%M", id(ha_time).now());
      it.strftime(210, 80, id(font_m), COLOR_OFF, TextAlign::BASELINE_LEFT, "%A, %d.%m.%Y", id(ha_time).now());
      it.line(0, 90, 600, 90, COLOR_OFF);
      it.line(0, 91, 600, 91, COLOR_OFF);
      it.line(0, 92, 600, 92, COLOR_OFF);

      it.printf(110, 495, id(font_m), COLOR_OFF, TextAlign::BASELINE_CENTER, "Hier");
      it.line(50, 500, 170, 500, COLOR_OFF);
      it.printf(170, 540, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "- °C");
      it.printf(170, 585, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "- %%");

      it.printf(270, 495, id(font_m), COLOR_OFF, TextAlign::BASELINE_CENTER, "Außen");
      it.line(220, 500, 340, 500, COLOR_OFF);
      it.printf(340, 540, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "- °C");
      it.printf(340, 585, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "- %%");

      it.printf(450, 495, id(font_m), COLOR_OFF, TextAlign::BASELINE_CENTER, "Arbeit");
      it.line(390, 500, 510, 500, COLOR_OFF);
      it.printf(510, 540, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "%.1f°C", id(az_temp).state);
      it.printf(510, 585, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "%.0f%%", id(az_hum).state);

      it.printf(620, 495, id(font_m), COLOR_OFF, TextAlign::BASELINE_CENTER, "Bad");
      it.line(560, 500, 680, 500, COLOR_OFF);
      it.printf(680, 540, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "- °C");
      it.printf(680, 585, id(font_m), COLOR_OFF, TextAlign::BASELINE_RIGHT, "- %%");

time:
  - platform: homeassistant
    id: ha_time
