esphome:
  name: wohnzimmer
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "Kerberos"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

font:
  - file: "DejaVuSans.ttf"
    id: font_m
    size: 18
  - file: "DejaVuSans.ttf"
    id: font_l
    size: 32

mcp23017:
  - id: mcp23017_hub
    address: 0x20

i2c:

display:
  - platform: inkplate6
    greyscale: false
    partial_updating: true
    update_interval: 60s
    rotation: 0°
    ckv_pin: 32
    sph_pin: 33
    gmod_pin:
      mcp23xxx: mcp23017_hub
      number: 1
    gpio0_enable_pin:
      mcp23xxx: mcp23017_hub
      number: 8
    oe_pin:
      mcp23xxx: mcp23017_hub
      number: 0
    spv_pin:
      mcp23xxx: mcp23017_hub
      number: 2
    powerup_pin:
      mcp23xxx: mcp23017_hub
      number: 4
    wakeup_pin:
      mcp23xxx: mcp23017_hub
      number: 3
    vcom_pin:
      mcp23xxx: mcp23017_hub
      number: 5
    lambda: |-
      it.strftime(400, 0, id(font_l), TextAlign::TOP_CENTER, "%H:%M", id(ha_time).now());

time:
  - platform: homeassistant
    id: ha_time
